import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from './_component/Header'
import "../style/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce with NextJS",
  description: "Generated by E-commerce with NextJS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 right-0 left-0">
          <Header></Header>
        </div>
        {children}
      </body>
    </html>
  );
}
