import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from './_component/Layout/Header'
import "../style/globals.css";
import Navbar from "./_component/Layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce with NextJS",
  description: "Generated by E-commerce with NextJS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <div className="container px-0 mt-16">
          <Navbar></Navbar>
          {children}
        </div>
      </body>
    </html>
  );
}
